services:
  db:
    image: postgres:15
    container_name: task_manager_db
    restart: always
    environment:
      POSTGRES_USER: saas_admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: task_manager_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: